version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Using Python 3.9 runtime..."
  build:
    commands:
      - echo "Packaging index Lambda function..."
      - cd lambda-functions/index
      - zip -r ../../index.zip *
      - echo "Index Lambda function packaged."

      - echo "Packaging search Lambda function..."
      - cd ../search
      - zip -r ../../search.zip *
      - echo "Search Lambda function packaged."
  post_build:
    commands:
      - echo "Updating original Lambda functions..."
      - aws lambda update-function-code --function-name LF1_A3 --zip-file fileb://index.zip
      - aws lambda update-function-code --function-name LF2_A3 --zip-file fileb://search.zip
      - echo "Original Lambda functions updated successfully."
